program   ::= { statement } exit
statement ::= decl NL | assign NL | if | while
decl      ::= type [ "mut" ] ident "{" expr "}"
type      ::= "i32" | "i64" | "bool"
assign    ::= ident ":=" expr
if        ::= "if" expr NL block [ "else" NL block ]
while     ::= "while" expr NL block
block     ::= "{" NL ( statement { statement } [ exit ] | exit ) "}" NL
exit      ::= "exit" factor NL
expr      ::= arith [ ( "==" | "!=" ) arith ]
arith     ::= term { ( "+" | "-" ) term }
term      ::= factor { "*" factor }
factor    ::= number | "true" | "false" | ident | "!" factor
ident     ::= ( letter | "_" ) { letter | digit | "_" }
number    ::= digit { digit }